const $ = s => document.querySelector(s);
const esc = x => String(x ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statuses = {queued:'等待执行',running:'分析中',succeeded:'已完成',failed:'分析失败'};
const state = {step:0,datasets:[],selected:null,preview:null,task:'',target:'',scope:'全部样本',criteria:'',parent:null,active:null,events:[],search:'',busy:false,token:sessionStorage.getItem('atlas-token')||''};
let poll, routeGeneration=0, objectUrls=[];
async function api(path, options={}) {
  const response = await fetch(path,{...options,headers:{'Content-Type':'application/json',...(state.token?{Authorization:`Bearer ${state.token}`} : {}),...options.headers}});
  if(!response.ok){let detail;try{detail=(await response.json()).detail}catch{};throw new Error(response.status===401?'需要 API token，请打开右下角连接设置。':typeof detail==='string'?detail:`请求失败（${response.status}）`)}
  return response.json();
}
function notice(message){$('#notice').textContent=message;$('#notice').hidden=false;clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('#notice').hidden=true,7000)}
function clearImages(){objectUrls.forEach(URL.revokeObjectURL);objectUrls=[]}
function frame(title,description){return `<div class="eyebrow">DATASET INTELLIGENCE</div><div class="page-title"><div><h1>${title}</h1><p>${description}</p></div><span class="badge">✧ 分布专家 · 评测前审查</span></div>`}
function steps(){return `<div class="steps">${['选择评测集','表达需求','补齐参数','确认提交'].map((label,i)=>`<div class="step ${i===state.step?'active':i<state.step?'done':''}"><span>${i<state.step?'✓':i+1}</span>${label}</div>`).join('')}</div>`}
function card(d){return `<button class="dataset-card ${state.selected?.id===d.id?'selected':''}" data-dataset="${esc(d.id)}"><div class="dataset-title"><span class="dataset-symbol">▤</span>${esc(d.name)}</div><span class="check">${state.selected?.id===d.id?'●':'○'}</span><div class="dataset-meta"><span>${esc(d.item_count??'—')} 条样本</span><span>${esc(d.version||'当前版本')}</span><span>${esc(d.created_at?new Date(d.created_at).toLocaleDateString():'日期未知')}</span></div><div class="tags">${(d.tags||[]).slice(0,4).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></button>`}
function aside(){const d=state.selected;return `<aside><div class="panel-subtle"><div class="tip-icon">✧</div><h3>让评测，从好问题开始</h3><p>先理解数据集覆盖了什么，再判断它能否回答你的评测问题。</p><div class="mini-heading">本次分析将关注</div><p>01　样本与类别分布<br>02　覆盖缺口与重复问题<br>03　与目标能力的匹配度</p></div>${d?`<div class="panel" style="margin-top:20px"><span class="hint">已选择数据集</span><h3 style="margin-top:8px;overflow-wrap:anywhere">${esc(d.name)}</h3><div class="preview-stat">${esc(d.item_count??'—')}<small>待测样本 · ${esc(d.version||'当前版本')}</small></div><span class="hint">不需要先运行模型评测</span></div>`:''}</aside>`}
function render(){clearImages();if(state.active){renderAnalysis();return}let body='';
 if(state.step===0){body=`<div class="panel"><div class="panel-head"><h2>选择一个评测集</h2><span class="hint">来自 Opik</span></div><input id="search" class="search" placeholder="搜索数据集名称…" aria-label="搜索数据集" value="${esc(state.search)}"><div id="dataset-list">${datasetList()}</div><div id="preview">${preview()}</div></div><div class="actions"><span class="hint back">分析只读取数据，不修改原始评测集</span><button id="next" class="primary" ${!state.selected?'disabled':''}>继续，表达需求 →</button></div>`}
 if(state.step===1){body=`<div class="panel"><h2>你想了解什么？</h2><p class="hint">描述使用场景和关注点，分布专家会围绕你的目标分析。</p><label for="task">分析需求</label><textarea id="task" maxlength="12000" placeholder="例如：这个评测集适合评估一个具备网页搜索和代码执行能力的 Agent 吗？重点检查多步任务覆盖。">${esc(state.task)}</textarea><div class="chips">${['检查任务覆盖是否充分','检查重复与缺失样本','判断是否适合我的 Agent'].map(x=>`<button class="chip" data-prompt="${x}">${x} ↗</button>`).join('')}</div></div><div class="actions"><button class="secondary back" id="back">← 返回</button><button class="primary" id="next">继续，补齐参数 →</button></div>`}
 if(state.step===2){body=`<div class="panel"><h2>补充一点背景，让结论更有依据</h2><p class="hint">没有标准答案的参数可以留空，我们会在报告中说明判断边界。</p><label for="target">待测 Agent 的目标能力 <span class="muted">· 建议填写</span></label><input id="target" maxlength="2000" placeholder="例如：网页检索、多步推理、Python 代码执行" value="${esc(state.target)}"><label for="scope">分析范围</label><input id="scope" maxlength="1000" value="${esc(state.scope)}" placeholder="全部样本，或仅 metadata.subset=gaia"><div class="hint">填写子集或筛选条件时，专家会在导出后筛选，并报告实际样本量。</div><label for="criteria">判断依据或期望分布 <span class="muted">· 可选</span></label><textarea id="criteria" maxlength="4000" placeholder="例如：以工具调用任务为主；希望覆盖单步和多步场景。没有指定标准时，报告只说明可见风险与局限。">${esc(state.criteria)}</textarea></div><div class="actions"><button class="secondary back" id="back">← 返回</button><button class="primary" id="next">查看提交摘要 →</button></div>`}
 if(state.step===3){body=`<div class="panel"><div class="panel-head"><h2>准备开始分析</h2><span class="badge">只读分析</span></div>${[['评测集',state.selected?.name],['数据版本',`${state.selected?.version||'当前版本'} · 执行时读取最新数据`],['分析需求',state.task],['目标能力',state.target||'未指定：限制适用性判断'],['分析范围',state.scope||'全部样本'],['判断依据',state.criteria||'未指定：不预设均衡比例']].map(([k,v])=>`<div class="review-row"><span>${k}</span><div>${esc(v)}</div></div>`).join('')}<p class="hint" style="margin-top:18px">提交后由分布专家读取数据、运行统计并生成报告。分析会调用已配置的模型，可能产生模型费用。</p></div><div class="actions"><button class="secondary back" id="back">← 修改参数</button><button class="primary" id="submit" ${state.busy?'disabled':''}>${state.busy?'正在提交…':'提交分析 ↗'}</button></div>`}
 $('#main').innerHTML=frame('每一次评测，都有据可依','了解数据分布，发现覆盖盲点，为你的 Agent 构建更可靠的评测。')+steps()+`<div class="content-grid"><section>${body}</section>${aside()}</div>`;
 $('#back')?.addEventListener('click',()=>{saveFields();state.step--;render()});$('#next')?.addEventListener('click',()=>{saveFields();if(state.step===1&&!state.task.trim()){notice('请先描述分析需求。');$('#task').focus();return}state.step++;render()});
 $('#search')?.addEventListener('input',e=>{state.search=e.target.value;$('#dataset-list').innerHTML=datasetList();bindDatasets()});bindDatasets();$('#submit')?.addEventListener('click',submit);
 document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{$('#task').value=b.dataset.prompt;state.task=b.dataset.prompt});
}
function saveFields(){for(const key of ['task','target','scope','criteria'])if($('#'+key))state[key]=$('#'+key).value}
function datasetList(){const rows=state.datasets.filter(d=>d.name.toLowerCase().includes(state.search.toLowerCase()));return rows.length?rows.map(card).join(''):`<div class="empty">${state.loadError?esc(state.loadError):state.loading?'正在连接 Opik…':'暂无匹配的数据集。请先在 Opik 导入评测集。'}<br><button id="retry-datasets" class="text-button" onclick="loadData()">重新加载 ↻</button></div>`}
function preview(){if(!state.selected)return '';if(!state.preview)return '<p class="hint">正在读取样本结构…</p>';if(state.preview.error)return `<p class="error">${esc(state.preview.error)}</p>`;const items=state.preview.items||[];const fields=[...new Set(items.flatMap(x=>Object.keys(x.metadata||{})))];return `<details><summary>预览字段与样本 <span class="hint">· 前 ${items.length} 条，不代表总体分布</span></summary><div class="preview-fields">${fields.map(k=>`<span class="tag">metadata.${esc(k)}</span>`).join('')}</div>${items.map((r,i)=>`<p><b>样本 ${i+1}</b>　${esc(typeof r.input==='string'?r.input:JSON.stringify(r.input)).slice(0,600)}</p>`).join('')}</details>`}
function bindDatasets(){document.querySelectorAll('[data-dataset]').forEach(b=>b.onclick=async()=>{state.selected=state.datasets.find(d=>d.id===b.dataset.dataset);state.preview=null;const id=state.selected.id;render();try{const data=await api(`/datasets/${encodeURIComponent(id)}/preview`);if(state.selected?.id!==id)return;state.preview=data}catch(e){if(state.selected?.id!==id)return;state.preview={error:e.message}}if(state.step===0&&!state.active)render()})}
async function loadData(){state.loading=true;state.loadError='';if(!state.active)render();try{state.datasets=await api('/datasets');$('#connection-dot').className='online';$('#connection-label').textContent='Opik 已连接'}catch(e){state.loadError=e.message;$('#connection-dot').className='';$('#connection-label').textContent='连接不可用'}state.loading=false;if(!state.active)render();await history()}
async function history(){try{const rows=await api('/analyses?limit=50');$('#history').innerHTML=rows.length?rows.map(r=>`<button data-analysis="${esc(r.id)}" class="${state.active?.id===r.id?'selected':''}"><span class="title">${esc(r.params?.dataset_name||r.task)}</span><small>${esc(statuses[r.status])} · ${new Date(r.created_at).toLocaleDateString()}</small></button>`).join(''):'<div class="hint" style="padding:12px">首份报告，从一次提问开始。</div>';document.querySelectorAll('[data-analysis]').forEach(b=>b.onclick=()=>openAnalysis(b.dataset.analysis))}catch(e){$('#history').textContent=e.message}}
async function submit(){if(state.busy)return;state.busy=true;render();try{const params={dataset_id:state.selected.id,dataset_name:state.selected.name,dataset_version:state.selected.version||null,analysis_request:state.task,target_capabilities:state.target,scope:state.scope||'全部样本',criteria:state.criteria,parent_analysis_id:state.parent};const task=`使用 dataset-distribution Skill 审查 Opik 待测数据集 ${state.selected.name}（id ${state.selected.id}）。\n需求：${state.task}\n目标能力：${state.target||'未指定，不作确定适用性判断'}\n范围：${state.scope||'全部样本'}\n依据：${state.criteria||'未指定，不预设均衡比例'}\n从 dataset_items 导出后按范围筛选，明确导出总量和分析样本量。统计必须经沙箱运行，报告覆盖局限并提供图表。`;const r=await api('/analyses',{method:'POST',body:JSON.stringify({task,params})});await openAnalysis(r.analysis_id)}catch(e){notice(e.message)}finally{state.busy=false;if(!state.active)render()}}
async function openAnalysis(id){clearTimeout(poll);const gen=++routeGeneration;try{const [row,events]=await Promise.all([api(`/analyses/${id}`),api(`/analyses/${id}/events?limit=1000`)]);if(gen!==routeGeneration)return;state.active=row;state.events=events;location.hash=id;render();history();if(['queued','running'].includes(row.status))poll=setTimeout(()=>openAnalysis(id),2500)}catch(e){notice(e.message);if(gen===routeGeneration&&state.active?.id===id&&['queued','running'].includes(state.active.status))poll=setTimeout(()=>openAnalysis(id),5000)}}
function eventLabel(e){const names={read_skill:'加载分析方法',sample_dataset_items:'读取样本',export_data:'导出数据集',run_in_sandbox:'运行统计分析',submit_result:'整理报告',list_datasets:'发现数据集'};if(e.type==='agent_step')return(e.tool_names||[]).map(n=>names[n]||n).join('、')||'专家正在推理';if(e.type==='export_data')return `导出 ${e.written} 条${e.truncated?'（已截断）':''}`;if(e.type==='sandbox_run')return `统计脚本${e.exit_code===0?'执行完成':'执行失败，将检查原因'}`;if(e.type==='mcp_call')return `数据读取${e.ok?'完成':'重试中'}`;return({agent_started:'分析已开始',report_followup:'报告追问'})[e.type]||e.type}
function renderAnalysis(){const r=state.active,ev=state.events.map(e=>e.event);$('#main').innerHTML=frame(r.params?.dataset_name||'分析任务',`报告工作台 · ${new Date(r.created_at).toLocaleString()} · ${statuses[r.status]}`)+(r.status==='succeeded'?report(r):progress(r,ev));$('#revise')?.addEventListener('click',revise);$('#download')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(r.result,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`report-${r.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});$('#ask-form')?.addEventListener('submit',ask);if(r.status==='succeeded')loadCharts(r);}
function progress(r,ev){const exported=ev.some(x=>x.type==='export_data'),ran=ev.some(x=>x.type==='sandbox_run'&&x.exit_code===0);let idx=r.status==='queued'?0:!exported?1:!ran?2:3;const titles=['等待执行','读取评测集','统计分布与专家审查','生成分析报告'];return `<div class="content-grid"><div class="panel"><span class="badge">${r.status==='failed'?'分析已停止':'实时状态'}</span><h2 style="margin-top:16px">${r.status==='failed'?'本次分析未完成':titles[idx]}</h2><p class="hint">${r.status==='queued'?'任务已入队，等待 Worker 接收。长时间排队请检查 Worker 是否运行。':'你可以离开此页，稍后从左侧历史继续查看。'}</p>${r.error?`<div class="error">${esc(r.error)}</div>`:''}<ol class="timeline">${titles.map((s,i)=>`<li class="${i<idx?'complete':i===idx?'current':''}"><span class="marker ${i===idx&&r.status!=='failed'?'pulse':''}">${i<idx?'✓':i+1}</span><div>${s}<small>${i<idx?'已完成':i===idx?statuses[r.status]:'等待前一步完成'}</small></div></li>`).join('')}</ol><details open><summary>运行记录</summary><div class="event-log">${state.events.slice(-30).map(x=>`${new Date(x.ts).toLocaleTimeString()}　${esc(eventLabel(x.event))}`).join('\n')||'暂无事件'}</div></details>${r.status==='failed'?'<button id="revise" class="secondary">调整参数并重试</button>':''}</div><aside class="panel-subtle"><h3>这次分析会发生什么？</h3><p>从 Opik 读取数据，执行统计脚本，再由分布专家结合目标能力解读结果。</p><p>进度来自任务事件，不代表预计剩余时间。</p></aside></div>`}
function report(r){const result=r.result,metrics=result.metrics||{},labels={sample_count:'分析样本量',duplicate_ratio:'重复题目比例',missing_expected_output_ratio:'参考答案缺失率',category_count:'类别数量',largest_category_ratio:'最大类别占比',gaia_count:'GAIA 样本'};return `<div class="report-heading"><div class="actions"><span class="status-badge back">✓ 分析已完成${r.params?.parent_analysis_id?' · 基于历史报告调整范围':''}</span><button id="download" class="secondary">下载报告 ↓</button><button id="revise" class="primary">调整范围 ↗</button></div></div><div class="report-grid"><section><div class="panel summary"><div class="eyebrow">EXPERT SUMMARY</div><h2 style="margin-top:8px">分布专家的判断</h2><p>${esc(result.summary)}</p></div><div class="metrics">${Object.entries(metrics).slice(0,6).map(([k,v])=>`<div class="metric"><strong>${k.includes('ratio')?(v*100).toFixed(1)+'%':Number(v).toLocaleString(undefined,{maximumFractionDigits:2})}</strong><small>${esc(labels[k]||k)}</small></div>`).join('')}</div><div class="panel"><h2>分布与证据</h2><div id="charts">${(result.charts||[]).length?'<p class="hint">正在载入图表…</p>':'<p class="hint">本报告未生成图表。</p>'}</div>${(result.findings||[]).map((f,i)=>`<details ${i===0?'open':''}><summary>${esc(f.title)}</summary><p>${esc(f.detail)}</p>${f.evidence?`<pre>${esc(f.evidence)}</pre>`:''}</details>`).join('')}</div><div class="panel"><h3>判断边界与方法局限</h3><p style="font-size:12px;white-space:pre-wrap">${esc(result.caveats||'报告未提供额外说明。')}</p><details><summary>完整指标</summary><pre>${esc(JSON.stringify(metrics,null,2))}</pre></details></div></section><aside class="panel chat"><span class="eyebrow">CONTINUE THE CONVERSATION</span><h2 style="margin-top:10px">和报告继续聊聊</h2><p>追问会基于已有报告回答。需要重新统计时，使用「调整范围」。</p><div class="chat-log" id="chat-log">${state.events.filter(x=>x.event.type==='report_followup').map(x=>`<div class="bubble user">${esc(x.event.question)}</div><div class="bubble">${esc(x.event.answer)}</div>`).join('')}</div><form id="ask-form"><label for="question">你的问题</label><textarea id="question" maxlength="4000" required placeholder="为什么这个分布会影响评测结论？"></textarea><button class="primary" id="ask-button">发送追问 ↑</button><p id="ask-status" class="chat-busy" role="status"></p></form></aside></div>`}
async function loadCharts(row){const target=$('#charts');target.innerHTML='';for(const path of row.result.charts||[]){const holder=document.createElement('div');target.append(holder);try{const url=`/analyses/${row.id}/artifacts/workspace/${path.split('/').map(encodeURIComponent).join('/')}`;const res=await fetch(url,{headers:state.token?{Authorization:`Bearer ${state.token}`}:{}});if(!res.ok)throw new Error('图表载入失败');const blob=await res.blob();if(!target.isConnected)return;if(blob.type.startsWith('image/')){const img=document.createElement('img');img.className='chart';img.alt='评测集分布统计图';img.src=URL.createObjectURL(blob);objectUrls.push(img.src);holder.append(img)}else holder.textContent='该产物不是可预览图片。'}catch(e){holder.textContent=e.message}}}
async function ask(e){e.preventDefault();const id=state.active.id,question=$('#question').value.trim();if(!question)return;$('#ask-button').disabled=true;$('#ask-status').textContent='分布专家正在阅读报告…';try{await api(`/analyses/${id}/followups`,{method:'POST',body:JSON.stringify({question})});if(state.active?.id===id)await openAnalysis(id)}catch(err){if(state.active?.id===id){$('#ask-status').textContent=err.message;$('#ask-button').disabled=false}}}
function revise(){const r=state.active,p=r.params||{};state.selected=state.datasets.find(d=>d.id===p.dataset_id)||(p.dataset_id?{id:p.dataset_id,name:p.dataset_name,version:p.dataset_version}:null);state.task=p.analysis_request||r.task;state.target=p.target_capabilities||'';state.scope=p.scope||'全部样本';state.criteria=p.criteria||'';state.parent=r.id;state.step=state.selected?2:0;state.active=null;routeGeneration++;clearTimeout(poll);location.hash='';render();notice('已沿用原报告参数。提交后会创建新分析，保留原报告。')}
$('#new-analysis').onclick=()=>{clearTimeout(poll);routeGeneration++;Object.assign(state,{active:null,step:0,selected:null,preview:null,task:'',target:'',scope:'全部样本',criteria:'',parent:null,busy:false});location.hash='';render()};
$('#refresh-history').onclick=history;$('#settings').onclick=()=>{$('#api-token').value=state.token;$('#connection-dialog').showModal()};$('#close-settings').onclick=()=>$('#connection-dialog').close();$('#connection-form').onsubmit=e=>{e.preventDefault();state.token=$('#api-token').value.trim();sessionStorage.setItem('atlas-token',state.token);$('#connection-dialog').close();loadData();if(state.active)openAnalysis(state.active.id)};
loadData();if(/^#[0-9a-f-]{36}$/i.test(location.hash))openAnalysis(location.hash.slice(1));
